# Generated by Django 5.0.6 on 2024-07-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('jantina', models.CharField(max_length=200, null=True)),
                ('noPekerja', models.CharField(max_length=200, null=True)),
                ('noIC', models.CharField(max_length=200, null=True)),
                ('noTel', models.CharField(max_length=200, null=True)),
                ('fakulti', models.CharField(max_length=200, null=True)),
                ('jbtnPTJ', models.CharField(max_length=200, null=True)),
                ('cawangan', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('emailAlt', models.CharField(max_length=200, null=True)),
                ('alamat', models.CharField(max_length=200, null=True)),
                ('tarikhPencen', models.CharField(max_length=200, null=True)),
                ('namaPW', models.CharField(max_length=200, null=True)),
                ('noTelPW', models.CharField(max_length=200, null=True)),
                ('data_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
