# Generated by Django 5.0.6 on 2024-07-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Menunggu Kelulusan', 'Menunggu Kelulusan'), ('Ahli MITASA', 'Ahli MITASA')], max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='jantina',
            field=models.CharField(choices=[('Lelaki', 'Lelaki'), ('Perempuan', 'Perempuan')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='jbtnPTJ',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='tarikhPencen',
            field=models.DateField(null=True),
        ),
    ]
