# Generated by Django 5.0.3 on 2024-07-09 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_membership_alter_member_jantina_alter_member_jbtnptj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='cawangan',
            field=models.CharField(choices=[('SHAH ALAM', 'SHAH ALAM'), ('PUNCAK ALAM', 'PUNCAK ALAM'), ('PUNCAK PERDANA', 'PUNCAK PERDANA'), ('SUNGAI BULOH', 'SUNGAI BULOH'), ('DENGKIL', 'DENGKIL'), ('SERI ISKANDAR', 'SERI ISKANDAR'), ('TAPAH', 'TAPAH'), ('SEGAMAT', 'SEGAMAT'), ('PASIR GUDANG', 'PASIR GUDANG'), ('SUNGAI PETANI', 'SUNGAI PETANI'), ('MACHANG', 'MACHANG'), ('KOTA BHARU', 'KOTA BHARU'), ('ALOR GAJAH', 'ALOR GAJAH'), ('BANDARAYA MELAKA', 'BANDARAYA MELAKA'), ('JASIN', 'JASIN'), ('KUALA PILAH', 'KUALA PILAH'), ('SEREMBAN', 'SEREMBAN'), ('REMBAU', 'REMBAU'), ('JENGKA', 'JENGKA'), ('RAUB', 'RAUB'), ('KUANTAN', 'KUANTAN'), ('PERMATANG PAUH', 'PERMATANG PAUH'), ('BERTAM', 'BERTAM'), ('ARAU', 'ARAU'), ('KUALA TERENGGANU', 'KUALA TERENGGANU'), ('BUKIT BESI', 'BUKIT BESI'), ('DUNGUN', 'DUNGUN'), ('KOTA KINABALU', 'KOTA KINABALU'), ('TAWAU', 'TAWAU'), ('SAMARAHAN 2', 'SAMARAHAN 2'), ('MUKAH', 'MUKAH'), ('Lain - Lain', 'Lain - Lain')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='fakulti',
            field=models.CharField(choices=[('FAKULTI FARMASI', 'FAKULTI FARMASI'), ('FAKULTI PERLADANGAN & AGROTEKNOLOGI', 'FAKULTI PERLADANGAN & AGROTEKNOLOGI'), ('FAKULTI SAINS KESIHATAN', 'FAKULTI SAINS KESIHATAN'), ('KOLEJ PENGAJIAN ALAM BINA', 'KOLEJ PENGAJIAN ALAM BINA'), ('KOLEJ PENGAJIAN KEJURUTERAAN', 'KOLEJ PENGAJIAN KEJURUTERAAN'), ('FAKULTI PERUBATAN', 'FAKULTI PERUBATAN'), ('KOLEJ PENGAJIAN PENGKOMPUTERAN, INFORMATIK & MATEMATIK', 'KOLEJ PENGAJIAN PENGKOMPUTERAN, INFORMATIK & MATEMATIK'), ('FAKULTI PERGIGIAN', 'FAKULTI PERGIGIAN'), ('FAKULTI SAINS GUNAAN', 'FAKULTI SAINS GUNAAN'), ('FAKULTI SAINS SUKAN & REKREASI', 'FAKULTI SAINS SUKAN & REKREASI'), ('KOLEJ PENGAJIAN SENI KREATIF', 'KOLEJ PENGAJIAN SENI KREATIF'), ('FAKULTI SAINS PENTADBIRAN & PENGAJIAN POLISI', 'FAKULTI SAINS PENTADBIRAN & PENGAJIAN POLISI'), ('FAKULTI KOMUNIKASI & PENGAJIAN MEDIA', 'FAKULTI KOMUNIKASI & PENGAJIAN MEDIA'), ('FAKULTI UNDANG-UNDANG', 'FAKULTI UNDANG-UNDANG'), ('FAKULTI PENDIDIKAN', 'FAKULTI PENDIDIKAN'), ('FAKULTI PENGURUSAN & PERNIAGAAN', 'FAKULTI PENGURUSAN & PERNIAGAAN'), ('FAKULTI PENGURUSAN HOTEL & PELANCONGAN', 'FAKULTI PENGURUSAN HOTEL & PELANCONGAN'), ('FAKULTI PERAKAUNAN', 'FAKULTI PERAKAUNAN'), ('Lain - Lain', 'Lain - Lain')], max_length=200, null=True),
        ),
    ]
