# Generated by Django 5.0.3 on 2024-07-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_membership_member_alter_member_cawangan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Menunggu Kelulusan', 'Menunggu Kelulusan'), ('Ahli MITASA', 'Ahli MITASA')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
