# Generated by Django 5.0.3 on 2024-07-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_member_status_delete_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Menunggu Kelulusan', 'Menunggu Kelulusan'), ('Ahli MITASA', 'Ahli MITASA')], default='Menunggu Kelulusan', max_length=200, null=True),
        ),
    ]
