# Generated by Django 5.0.3 on 2024-07-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bangsa',
            field=models.CharField(choices=[('Melayu', 'Melayu'), ('Cina', 'Cina'), ('India', 'India'), ('Sabah', 'Sabah'), ('Sarawak', 'Sarawak'), ('Lain-Lain', 'Lain-Lain')], max_length=200, null=True),
        ),
    ]
