# Generated by Django 5.0.3 on 2024-07-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_member_bangsa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='noPekerja',
        ),
    ]
