# Generated by Django 5.0.3 on 2024-07-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_memberfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberfee',
            name='jbtn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='memberfee',
            name='keterangan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='memberfee',
            name='kod',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
