# Generated by Django 5.0.3 on 2024-07-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_alter_memberfee_jbtn_alter_memberfee_keterangan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='noPekerja',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
