# Generated by Django 5.0.3 on 2024-07-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_alter_memberfee_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberfee',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='memberfee',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberfee',
            name='nama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='memberfee',
            name='noIC',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='memberfee',
            name='noPekerja',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
