# Generated by Django 5.0.3 on 2024-07-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_alter_memberfee_amount_alter_memberfee_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tarikhLahir',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(blank=True, choices=[('Not a Member', 'Not a Member'), ('New Member', 'New Member'), ('Member', 'Member'), ('Anomaly', 'Anomaly')], default='Waiting for Approval', max_length=200, null=True),
        ),
    ]
