# Generated by Django 5.0.3 on 2024-07-24 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_member_tarikhlahir_alter_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberfee',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='member.member'),
        ),
    ]
